name: Release_AAR

on:
  push:
    branches:
      - "master"
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
 android:
    runs-on: ubuntu-latest
    env:
      output: "${{ github.workspace }}/build/app/outputs/apk/release"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download AList Source Code
        run: |
          cd $GITHUB_WORKSPACE/alist-lib/scripts
          chmod +x *.sh
          ./init_alist.sh
          ./init_web.sh

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ${{ github.workspace }}/alist-lib/alist/go.sum

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build AList
        run: |
            cd $GITHUB_WORKSPACE/alist-lib/scripts
            chmod +x *.sh
            ./init_gomobile.sh
            ./gobind.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload AAR
        uses: actions/upload-artifact@v3
        with:
          name: "AList"
          path: "${{ github.workspace }}/android/app/libs/*.aar"
